baseURL: "https://nlaurent9816.github.io/theBlogProject/"
languageCode: "fr-fr"
title: "The Blog Project"
theme: "ananke"
defaultContentLanguage: fr

params:
  show_reading_time: false
  background_color_class: "bg-navy"
  body_classes: "serif"
  post_content_classes: "sans-serif post-content"
  recent_posts_number: 8
  custom_css: 
    - "css/custom.css"
    - "css/accordion.css"

menu:
  main:
  - name: Articles "jeu vidéo"
    url: /tags/jeu-vidéo/
    weight: -200
  - name: À propos
    url: /apropos
    weight: -100
